apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sharppcap
  description: Official repository - Fully managed, cross platform (Windows, Mac, Linux) .NET library for capturing packets
  annotations:
    github.com/project-slug: Lansweeper/sharppcap
spec:
  type: github-repository
  owner: unknown
  lifecycle: stable