version: 2.1

parameters:
  csproj-file:
    type: string
    default: "SharpPcap/SharpPcap.csproj"
  nuget-output-folder:
    type: string
    default: "SharpPcap/bin/Release"

executors:
  node:
    docker:
      - image: circleci/node:12

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: dotnet build << pipeline.parameters.csproj-file >> --configuration Release
      - persist_to_workspace:
          root: .
          paths:
            - .

  nuget-prepare:
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Create local nuget config file
          command: |
            $xml = "<?xml version='1.0' encoding='utf-8'?>
            <configuration>
              <packageSources>
                <add key='github' value='https://nuget.pkg.github.com/Lansweeper/index.json' />
              </packageSources>
              <packageSourceCredentials>
                <github>
                  <add key='Username' value='$env:GITHUB_USER' />
                  <add key='ClearTextPassword' value='$env:GITHUB_TOKEN' />
                </github>
              </packageSourceCredentials>
            </configuration>"
            Out-File -FilePath nuget.config -InputObject $xml -Encoding ASCII
      - run: type nuget.config
      - persist_to_workspace:
          root: .
          paths:
            - .

  nuget-publish:
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Pack the default package
          command: dotnet pack << pipeline.parameters.csproj-file >> --configuration Release
      - run:
          name: Publish the default package
          shell: bash
          command: |
            version=$(grep -o "<Version>[^<]*" << pipeline.parameters.csproj-file >> | sed 's/<Version>//' | head -n 1)
            packageid=$(grep -o "<PackageId>[^<]*" << pipeline.parameters.csproj-file >> | sed 's/<PackageId>//' | head -n 1)
            dotnet nuget push << pipeline.parameters.nuget-output-folder >>/$packageid.$version.nupkg --source "github" --api-key $GITHUB_TOKEN

workflows:
  version: 2

  ci_on_pr:
    jobs:
      - build:
          context:
            - lec-github-packages-rw
          filters:
            branches:
              ignore: master
  ci_and_release_master:
    jobs:
      - build:
          context:
            - lec-github-packages-rw
          filters:
            branches:
              only: master
      - nuget-prepare:
          requires:
            - build
          context:
            - lec-github-packages-rw
          filters:
            branches:
              only: master
      - nuget-publish:
          requires:
            - nuget-prepare
          context:
            - lec-github-packages-rw
          filters:
            branches:
              only: master
